import { 
  AlertCircleIcon, 
  BellDotIcon, 
  ComponentIcon, 
  LayoutDashboardIcon, 
  SidebarIcon, 
  WandIcon,
  FileTextIcon, 
  MessageCircleIcon,
  SquareIcon,
  UserIcon,
  StarIcon,
  ArrowRightIcon,
  MousePointerClickIcon,
  LayersIcon,
  CalendarIcon,
  CreditCardIcon,
  ArrowLeftRightIcon,
  CheckSquareIcon,
  ChevronDownIcon,
  SearchIcon,
  CommandIcon,
  MoreVerticalIcon,
  MessageSquareIcon,
  PanelLeftIcon,
  InboxIcon,
  TypeIcon,
  HashIcon,
  HelpCircleIcon,
  TagIcon,
  MenuIcon,
  ArrowLeftIcon,
  BarChart3Icon,
  CircleDotIcon,
  ExpandIcon,
  ArrowDownIcon,
  ChevronsUpDownIcon,
  MinusIcon,
  PanelRightIcon,
  LoaderIcon,
  SlidersIcon,
  PowerIcon,
  TableIcon,
  AlignLeftIcon,
  FolderRootIcon,
  AlertTriangleIcon,
  RatioIcon,
  UserCircleIcon,
  BadgeIcon,
  NavigationIcon,
  BoxIcon,
  GalleryHorizontalIcon,
  TerminalIcon,
  RectangleHorizontalIcon,
  PanelTopIcon,
  CircleIcon,
  FileInputIcon,
  TextCursorInputIcon,
  UngroupIcon,
  ShieldIcon,
  KeyboardIcon,
  CompassIcon,
  ListOrderedIcon,
  PopcornIcon,
  BoomBoxIcon,
  GripVerticalIcon,
  MouseIcon,
  LassoSelectIcon,
  PanelsRightBottomIcon,
  SlidersHorizontalIcon,
  BellIcon,
  Loader2Icon,
  ToggleLeftIcon,
  PanelTopIcon as TabsIcon,
  SquarePenIcon,
  EclipseIcon,
  Settings2Icon,
  ActivityIcon,
  GitBranchIcon,
  BrainIcon,
  CheckIcon,
  CodeIcon,
  VoteIcon,
  InfoIcon,
  MessagesSquareIcon,
  ImageIcon,
  LinkIcon,
  QuoteIcon,
  MessageSquareDotIcon,
  BotIcon,
  MessageSquareShareIcon,
  MessageSquareQuoteIcon,
  ListEndIcon,
  SparklesIcon,
  BookOpenIcon,
  LightbulbIcon,
  CalendarCheckIcon,
  WrenchIcon,
  GlobeIcon,
} from "lucide-react"

// Category configuration with icons
export const categoryConfig: Record<
  string,
  { icon: React.FC; label?: string }
> = {
  ai: { icon: WandIcon, label: "AI" },
  ui: { icon: ComponentIcon, label: "UI" },
  sidebar: { icon: SidebarIcon, label: "Sidebar" },
  dashboards: { icon: LayoutDashboardIcon, label: "Dashboards" },
  chat: { icon: MessageCircleIcon, label: "Chat" },
  page: { icon: FileTextIcon, label: "Page" },
}

type ComponentConfig = {
  name: string
  component?: React.ComponentType
  className?: string
  type: "registry:ui" | "registry:page" | "registry:block"
  href: string
  label?: string
  icon?: React.FC
  category?: string
}

export const componentRegistry: Record<string, ComponentConfig> = {
  // UI Components
  accordion: {
    name: "Accordion",
    type: "registry:ui",
    href: "/accordion",
    icon: FolderRootIcon,
    category: "ui",
  },
  alert: {
    name: "Alert",
    type: "registry:ui",
    href: "/alert",
    icon: AlertTriangleIcon,
    category: "ui",
  },
  "alert-dialog": {
    name: "Alert Dialog",
    type: "registry:ui",
    href: "/alert-dialog",
    icon: AlertCircleIcon,
    category: "ui",
  },
  "aspect-ratio": {
    name: "Aspect Ratio",
    type: "registry:ui",
    href: "/aspect-ratio",
    icon: RatioIcon,
    category: "ui",
  },
  avatar: {
    name: "Avatar",
    type: "registry:ui",
    href: "/avatar",
    icon: UserCircleIcon,
    category: "ui",
  },
  badge: {
    name: "Badge",
    type: "registry:ui",
    href: "/badge",
    icon: BadgeIcon,
    category: "ui",
  },
  breadcrumb: {
    name: "Breadcrumb",
    type: "registry:ui",
    href: "/breadcrumb",
    icon: NavigationIcon,
    category: "ui",
  },
  button: {
    name: "Button",
    type: "registry:ui",
    href: "/button",
    icon: SquareIcon,
    category: "ui",
  },
  "button-group": {
    name: "Button Group",
    type: "registry:ui",
    href: "/button-group",
    label: "New",
    icon: MousePointerClickIcon,
    category: "ui",
  },
  calendar: {
    name: "Calendar",
    type: "registry:ui",
    href: "/calendar",
    icon: CalendarIcon,
    category: "ui",
  },
  card: {
    name: "Card",
    type: "registry:ui",
    href: "/card",
    icon: CreditCardIcon,
    category: "ui",
  },
  carousel: {
    name: "Carousel",
    type: "registry:ui",
    href: "/carousel",
    icon: GalleryHorizontalIcon,
    category: "ui",
  },
  chart: {
    name: "Chart",
    className: "w-full",
    type: "registry:ui",
    href: "/chart",
    icon: BoxIcon,
    category: "ui",
  },
  checkbox: {
    name: "Checkbox",
    type: "registry:ui",
    href: "/checkbox",
    icon: CheckSquareIcon,
    category: "ui",
  },
  collapsible: {
    name: "Collapsible",
    type: "registry:ui",
    href: "/collapsible",
    icon: ChevronDownIcon,
    category: "ui",
  },
  combobox: {
    name: "Combobox",
    type: "registry:ui",
    href: "/combobox",
    icon: TerminalIcon,
    category: "ui",
  },
  command: {
    name: "Command",
    type: "registry:ui",
    href: "/command",
    icon: CommandIcon,
    category: "ui",
  },
  "context-menu": {
    name: "Context Menu",
    type: "registry:ui",
    href: "/context-menu",
    icon: MenuIcon,
    category: "ui",
  },
  "data-table": {
    name: "Data Table",
    type: "registry:ui",
    href: "/data-table",
    icon: TableIcon,
    category: "ui",
  },
  "date-picker": {
    name: "Date Picker",
    type: "registry:ui",
    href: "/date-picker",
    icon: CalendarIcon,
    category: "ui",
  },
  dialog: {
    name: "Dialog",
    type: "registry:ui",
    href: "/dialog",
    icon: RectangleHorizontalIcon,
    category: "ui",
  },
  drawer: {
    name: "Drawer",
    type: "registry:ui",
    href: "/drawer",
    icon: PanelTopIcon,
    category: "ui",
  },
  "dropdown-menu": {
    name: "Dropdown Menu",
    type: "registry:ui",
    href: "/dropdown-menu",
    icon: ChevronDownIcon,
    category: "ui",
  },
  empty: {
    name: "Empty",
    type: "registry:ui",
    href: "/empty",
    label: "New",
    icon: CircleIcon,
    category: "ui",
  },
  field: {
    name: "Field",
    type: "registry:ui",
    href: "/field",
    label: "New",
    icon: FileTextIcon,
    category: "ui",
  },
  form: {
    name: "Form",
    type: "registry:ui",
    href: "/form",
    icon: FileInputIcon,
    category: "ui",
  },
  "hover-card": {
    name: "Hover Card",
    type: "registry:ui",
    href: "/hover-card",
    icon: CreditCardIcon,
    category: "ui",
  },
  input: {
    name: "Input",
    type: "registry:ui",
    href: "/input",
    icon: TextCursorInputIcon,
    category: "ui",
  },
  "input-group": {
    name: "Input Group",
    type: "registry:ui",
    href: "/input-group",
    label: "New",
    icon: UngroupIcon,
    category: "ui",
  },
  "input-otp": {
    name: "Input OTP",
    type: "registry:ui",
    href: "/input-otp",
    icon: ShieldIcon,
    category: "ui",
  },
  item: {
    name: "Item",
    type: "registry:ui",
    href: "/item",
    label: "New",
    icon: CircleIcon,
    category: "ui",
  },
  kbd: {
    name: "Kbd",
    type: "registry:ui",
    href: "/kbd",
    label: "New",
    icon: KeyboardIcon,
    category: "ui",
  },
  label: {
    name: "Label",
    type: "registry:ui",
    href: "/label",
    icon: TagIcon,
    category: "ui",
  },
  menubar: {
    name: "Menubar",
    type: "registry:ui",
    href: "/menubar",
    icon: MenuIcon,
    category: "ui",
  },
  "navigation-menu": {
    name: "Navigation Menu",
    type: "registry:ui",
    href: "/navigation-menu",
    icon: CompassIcon,
    category: "ui",
  },
  "native-select": {
    name: "Native Select",
    type: "registry:ui",
    href: "/native-select",
    label: "New",
    icon: ChevronDownIcon,
    category: "ui",
  },
  pagination: {
    name: "Pagination",
    type: "registry:ui",
    href: "/pagination",
    icon: ListOrderedIcon,
    category: "ui",
  },
  popover: {
    name: "Popover",
    type: "registry:ui",
    href: "/popover",
    icon: PopcornIcon,
    category: "ui",
  },
  progress: {
    name: "Progress",
    type: "registry:ui",
    href: "/progress",
    icon: MinusIcon,
    category: "ui",
  },
  "radio-group": {
    name: "Radio Group",
    type: "registry:ui",
    href: "/radio-group",
    icon: BoomBoxIcon,
    category: "ui",
  },
  resizable: {
    name: "Resizable",
    type: "registry:ui",
    href: "/resizable",
    icon: GripVerticalIcon,
    category: "ui",
  },
  "scroll-area": {
    name: "Scroll Area",
    type: "registry:ui",
    href: "/scroll-area",
    icon: MouseIcon,
    category: "ui",
  },
  select: {
    name: "Select",
    type: "registry:ui",
    href: "/select",
    icon: LassoSelectIcon,
    category: "ui",
  },
  separator: {
    name: "Separator",
    type: "registry:ui",
    href: "/separator",
    icon: MinusIcon,
    category: "ui",
  },
  sheet: {
    name: "Sheet",
    type: "registry:ui",
    href: "/sheet",
    icon: PanelsRightBottomIcon,
    category: "ui",
  },
  sidebar: {
    name: "Sidebar",
    type: "registry:ui",
    href: "/sidebar",
    icon: SidebarIcon,
    category: "ui",
  },
  skeleton: {
    name: "Skeleton",
    type: "registry:ui",
    href: "/skeleton",
    icon: RectangleHorizontalIcon,
    category: "ui",
  },
  slider: {
    name: "Slider",
    type: "registry:ui",
    href: "/slider",
    icon: SlidersHorizontalIcon,
    category: "ui",
  },
  sonner: {
    name: "Sonner",
    type: "registry:ui",
    href: "/sonner",
    icon: BellIcon,
    category: "ui",
  },
  spinner: {
    name: "Spinner",
    type: "registry:ui",
    href: "/spinner",
    label: "New",
    icon: Loader2Icon,
    category: "ui",
  },
  switch: {
    name: "Switch",
    type: "registry:ui",
    href: "/switch",
    icon: ToggleLeftIcon,
    category: "ui",
  },
  table: {
    name: "Table",
    type: "registry:ui",
    href: "/table",
    icon: TableIcon,
    category: "ui",
  },
  tabs: {
    name: "Tabs",
    type: "registry:ui",
    href: "/tabs",
    icon: PanelTopIcon,
    category: "ui",
  },
  textarea: {
    name: "Textarea",
    type: "registry:ui",
    href: "/textarea",
    icon: SquarePenIcon,
    category: "ui",
  },
  toggle: {
    name: "Toggle",
    type: "registry:ui",
    href: "/toggle",
    icon: EclipseIcon,
    category: "ui",
  },
  "toggle-group": {
    name: "Toggle Group",
    type: "registry:ui",
    href: "/toggle-group",
    icon: Settings2Icon,
    category: "ui",
  },
  tooltip: {
    name: "Tooltip",
    type: "registry:ui",
    href: "/tooltip",
    icon: UserCircleIcon,
    category: "ui",
  },

  // AI Components
  actions: {
    name: "Actions",
    type: "registry:ui",
    href: "/actions",
    icon: ActivityIcon,
    category: "ai",
  },
  artifact: {
    name: "Artifact",
    type: "registry:ui",
    href: "/artifact",
    icon: ActivityIcon,
    category: "ai",
  },
  branch: {
    name: "Branch",
    type: "registry:ui",
    href: "/branch",
    icon: GitBranchIcon,
    category: "ai",
  },
  "chain-of-thought": {
    name: "Chain of Thought",
    type: "registry:ui",
    href: "/chain-of-thought",
    icon: BrainIcon,
    category: "ai",
  },
  checkpoint: {
    name: "Checkpoint",
    type: "registry:ui",
    href: "/checkpoint",
    icon: CheckIcon,
    category: "ai",
  },
  "code-block": {
    name: "Code Block",
    type: "registry:ui",
    href: "/code-block",
    icon: CodeIcon,
    category: "ai",
  },
  confirmation: {
    name: "Confirmation",
    type: "registry:ui",
    href: "/confirmation",
    icon: VoteIcon,
    category: "ai",
  },
  context: {
    name: "Context",
    type: "registry:ui",
    href: "/context",
    icon: InfoIcon,
    category: "ai",
  },
  conversation: {
    name: "Conversation",
    type: "registry:ui",
    href: "/conversation",
    icon: MessagesSquareIcon,
    category: "ai",
  },
  feedbackbar: {
    name: "Feedback Bar",
    type: "registry:ui",
    href: "/feedbackbar",
    icon: InfoIcon,
    category: "ai",
  },
  image: {
    name: "Image",
    type: "registry:ui",
    href: "/image",
    icon: ImageIcon,
    category: "ai",
  },
  loader: {
    name: "Loader",
    type: "registry:ui",
    href: "/loader",
    icon: LoaderIcon,
    category: "ai",
  },
  links: {
    name: "Links",
    type: "registry:ui",
    href: "/links",
    icon: LinkIcon,
    category: "ai",
  },
  "inline-citation": {
    name: "Inline Citation",
    type: "registry:ui",
    href: "/inline-citation",
    icon: QuoteIcon,
    category: "ai",
  },
  message: {
    name: "Message",
    type: "registry:ui",
    href: "/message",
    icon: MessageSquareDotIcon,
    category: "ai",
  },
  "model-selector": {
    name: "Model Selector",
    type: "registry:ui",
    href: "/model-selector",
    icon: BotIcon,
    category: "ai",
  },
  "open-in-chat": {
    name: "Open in Chat",
    type: "registry:ui",
    href: "/open-in-chat",
    icon: MessageSquareShareIcon,
    category: "ai",
  },
  plan: {
    name: "Plan",
    type: "registry:ui",
    href: "/plan",
    icon: CheckSquareIcon,
    category: "ai",
  },
  "prompt-input": {
    name: "Prompt Input",
    type: "registry:ui",
    href: "/prompt-input",
    icon: MessageSquareQuoteIcon,
    category: "ai",
  },
  queue: {
    name: "Queue",
    type: "registry:ui",
    href: "/queue",
    icon: ListEndIcon,
    category: "ai",
  },
  reasoning: {
    name: "Reasoning",
    type: "registry:ui",
    href: "/reasoning",
    icon: BrainIcon,
    category: "ai",
  },
  response: {
    name: "Response",
    type: "registry:ui",
    href: "/response",
    icon: TextCursorInputIcon,
    category: "ai",
  },
  shimmer: {
    name: "Shimmer",
    type: "registry:ui",
    href: "/shimmer",
    icon: SparklesIcon,
    category: "ai",
  },
  sources: {
    name: "Sources",
    type: "registry:ui",
    href: "/sources",
    icon: BookOpenIcon,
    category: "ai",
  },
  suggestions: {
    name: "Suggestions",
    type: "registry:ui",
    href: "/suggestions",
    icon: LightbulbIcon,
    category: "ai",
  },
  task: {
    name: "Task",
    type: "registry:ui",
    href: "/task",
    icon: CalendarCheckIcon,
    category: "ai",
  },
  tool: {
    name: "Tool",
    type: "registry:ui",
    href: "/tool",
    icon: WrenchIcon,
    category: "ai",
  },
  "web-preview": {
    name: "Web Preview",
    type: "registry:ui",
    href: "/web-preview",
    icon: GlobeIcon,
    category: "ai",
  },
}

export type ComponentKey = keyof typeof componentRegistry
