import { 
    AlertCircleIcon, 
    BellDotIcon, 
    ComponentIcon, 
    LayoutDashboardIcon, 
    SidebarIcon, 
    WandIcon,
    FileTextIcon, 
    MessageCircleIcon,
    SquareIcon,
    UserIcon,
    StarIcon,
    ArrowRightIcon,
    MousePointerClickIcon,
    LayersIcon,
    CalendarIcon,
    CreditCardIcon,
    ArrowLeftRightIcon,
    CheckSquareIcon,
    ChevronDownIcon,
    SearchIcon,
    CommandIcon,
    MoreVerticalIcon,
    MessageSquareIcon,
    PanelLeftIcon,
    InboxIcon,
    TypeIcon,
    HashIcon,
    HelpCircleIcon,
    TagIcon,
    MenuIcon,
    ArrowLeftIcon,
    BarChart3Icon,
    CircleDotIcon,
    ExpandIcon,
    ArrowDownIcon,
    ChevronsUpDownIcon,
    MinusIcon,
    PanelRightIcon,
    LoaderIcon,
    SlidersIcon,
    PowerIcon,
    TableIcon,
    AlignLeftIcon,
    FolderRootIcon,
  } from "lucide-react"
  
  // Category configuration with icons
  export const categoryConfig: Record<
    string,
    { icon: React.FC; label?: string }
  > = {
    ai: { icon: WandIcon, label: "AI" },
    ui: { icon: ComponentIcon, label: "UI" },
    sidebar: { icon: SidebarIcon, label: "Sidebar" },
    dashboards: { icon: LayoutDashboardIcon, label: "Dashboards" },
    chat: { icon: MessageCircleIcon, label: "Chat" },
    page: { icon: FileTextIcon, label: "Page" },
  }

  type ComponentConfig = {
    name: string
    component?: React.ComponentType
    className?: string
    type: "registry:ui" | "registry:page" | "registry:block"
    href: string
    label?: string
    icon?: React.FC
    category?: string
  }
  
  export const componentRegistry: Record<string, ComponentConfig> = {
    accordion: {
      name: "Accordion",
      type: "registry:ui",
      href: "/accordion",
      icon: FolderRootIcon,
      category: "ui",
    },
    alert: {
      name: "Alert",
      type: "registry:ui",
      href: "/alert",
      icon: BellDotIcon,
      category: "ui",
    },
    "alert-dialog": {
      name: "Alert Dialog",
      type: "registry:ui",
      href: "/alert-dialog",
      icon: AlertCircleIcon,
      category: "ui",
    },
    "aspect-ratio": {
      name: "Aspect Ratio",
      type: "registry:ui",
      href: "/aspect-ratio",
      icon: SquareIcon,
      category: "ui",
    },
    avatar: {
      name: "Avatar",
      type: "registry:ui",
      href: "/avatar",
      icon: UserIcon,
      category: "ui",
    },
    badge: {
      name: "Badge",
      type: "registry:ui",
      href: "/badge",
      icon: StarIcon,
      category: "ui",
    },
    breadcrumb: {
      name: "Breadcrumb",
      type: "registry:ui",
      href: "/breadcrumb",
      icon: ArrowRightIcon,
      category: "ui",
    },
    button: {
      name: "Button",
      type: "registry:ui",
      href: "/button",
      icon: MousePointerClickIcon,
      category: "ui",
    },
    "button-group": {
      name: "Button Group",
      type: "registry:ui",
      href: "/button-group",
      label: "New",
      icon: LayersIcon,
      category: "ui",
    },
    calendar: {
      name: "Calendar",
      type: "registry:ui",
      href: "/calendar",
      icon: CalendarIcon,
      category: "ui",
    },
    card: {
      name: "Card",
      type: "registry:ui",
      href: "/card",
      icon: CreditCardIcon,
      category: "ui",
    },
    carousel: {
      name: "Carousel",
      type: "registry:ui",
      href: "/carousel",
      icon: ArrowLeftRightIcon,
      category: "ui",
    },
    chart: {
      name: "Chart",
      className: "w-full",
      type: "registry:ui",
      href: "/chart",
      icon: BarChart3Icon,
      category: "ui",
    },
    checkbox: {
      name: "Checkbox",
      type: "registry:ui",
      href: "/checkbox",
      icon: CheckSquareIcon,
      category: "ui",
    },
    collapsible: {
      name: "Collapsible",
      type: "registry:ui",
      href: "/collapsible",
      icon: ChevronDownIcon,
      category: "ui",
    },
    combobox: {
      name: "Combobox",
      type: "registry:ui",
      href: "/combobox",
      icon: SearchIcon,
      category: "ui",
    },
    command: {
      name: "Command",
      type: "registry:ui",
      href: "/command",
      icon: CommandIcon,
      category: "ui",
    },
    "context-menu": {
      name: "Context Menu",
      type: "registry:ui",
      href: "/context-menu",
      icon: MoreVerticalIcon,
      category: "ui",
    },
    "date-picker": {
      name: "Date Picker",
      type: "registry:ui",
      href: "/date-picker",
      icon: CalendarIcon,
      category: "ui",
    },
    dialog: {
      name: "Dialog",
      type: "registry:ui",
      href: "/dialog",
      icon: MessageSquareIcon,
      category: "ui",
    },
    drawer: {
      name: "Drawer",
      type: "registry:ui",
      href: "/drawer",
      icon: PanelLeftIcon,
      category: "ui",
    },
    "dropdown-menu": {
      name: "Dropdown Menu",
      type: "registry:ui",
      href: "/dropdown-menu",
      icon: ChevronDownIcon,
      category: "ui",
    },
    empty: {
      name: "Empty",
      type: "registry:ui",
      href: "/empty",
      label: "New",
      icon: InboxIcon,
      category: "ui",
    },
    field: {
      name: "Field",
      type: "registry:ui",
      href: "/field",
      label: "New",
      icon: FileTextIcon,
      category: "ui",
    },
    form: {
      name: "Form",
      type: "registry:ui",
      href: "/form",
      icon: FileTextIcon,
      category: "ui",
    },
    "hover-card": {
      name: "Hover Card",
      type: "registry:ui",
      href: "/hover-card",
      icon: MousePointerClickIcon,
      category: "ui",
    },
    input: {
      name: "Input",
      type: "registry:ui",
      href: "/input",
      icon: TypeIcon,
      category: "ui",
    },
    "input-group": {
      name: "Input Group",
      type: "registry:ui",
      href: "/input-group",
      label: "New",
      icon: LayersIcon,
      category: "ui",
    },
    "input-otp": {
      name: "Input OTP",
      type: "registry:ui",
      href: "/input-otp",
      icon: HashIcon,
      category: "ui",
    },
    item: {
      name: "Item",
      type: "registry:ui",
      href: "/item",
      label: "New",
      icon: FileTextIcon,
      category: "ui",
    },
    kbd: {
      name: "Kbd",
      type: "registry:ui",
      href: "/kbd",
      label: "New",
      icon: CommandIcon,
      category: "ui",
    },
    label: {
      name: "Label",
      type: "registry:ui",
      href: "/label",
      icon: TagIcon,
      category: "ui",
    },
    menubar: {
      name: "Menubar",
      type: "registry:ui",
      href: "/menubar",
      icon: MenuIcon,
      category: "ui",
    },
    "navigation-menu": {
      name: "Navigation Menu",
      type: "registry:ui",
      href: "/navigation-menu",
      icon: MenuIcon,
      category: "ui",
    },
    "native-select": {
      name: "Native Select",
      type: "registry:ui",
      href: "/native-select",
      label: "New",
      icon: ChevronDownIcon,
      category: "ui",
    },
    pagination: {
      name: "Pagination",
      type: "registry:ui",
      href: "/pagination",
      icon: ArrowLeftIcon,
      category: "ui",
    },
    popover: {
      name: "Popover",
      type: "registry:ui",
      href: "/popover",
      icon: MessageCircleIcon,
      category: "ui",
    },
    progress: {
      name: "Progress",
      type: "registry:ui",
      href: "/progress",
      icon: BarChart3Icon,
      category: "ui",
    },
    "radio-group": {
      name: "Radio Group",
      type: "registry:ui",
      href: "/radio-group",
      icon: CircleDotIcon,
      category: "ui",
    },
    resizable: {
      name: "Resizable",
      type: "registry:ui",
      href: "/resizable",
      icon: ExpandIcon,
      category: "ui",
    },
    "scroll-area": {
      name: "Scroll Area",
      type: "registry:ui",
      href: "/scroll-area",
      icon: ArrowDownIcon,
      category: "ui",
    },
    select: {
      name: "Select",
      type: "registry:ui",
      href: "/select",
      icon: ChevronsUpDownIcon,
      category: "ui",
    },
    separator: {
      name: "Separator",
      type: "registry:ui",
      href: "/separator",
      icon: MinusIcon,
      category: "ui",
    },
    sheet: {
      name: "Sheet",
      type: "registry:ui",
      href: "/sheet",
      icon: PanelRightIcon,
      category: "ui",
    },
    skeleton: {
      name: "Skeleton",
      type: "registry:ui",
      href: "/skeleton",
      icon: LoaderIcon,
      category: "ui",
    },
    slider: {
      name: "Slider",
      type: "registry:ui",
      href: "/slider",
      icon: SlidersIcon,
      category: "ui",
    },
    sonner: {
      name: "Sonner",
      type: "registry:ui",
      href: "/sonner",
      icon: BellDotIcon,
      category: "ui",
    },
    spinner: {
      name: "Spinner",
      type: "registry:ui",
      href: "/spinner",
      label: "New",
      icon: LoaderIcon,
      category: "ui",
    },
    switch: {
      name: "Switch",
      type: "registry:ui",
      href: "/switch",
      icon: PowerIcon,
      category: "ui",
    },
    table: {
      name: "Table",
      type: "registry:ui",
      href: "/table",
      icon: TableIcon,
      category: "ui",
    },
    tabs: {
      name: "Tabs",
      type: "registry:ui",
      href: "/tabs",
      icon: LayersIcon,
      category: "ui",
    },
    textarea: {
      name: "Textarea",
      type: "registry:ui",
      href: "/textarea",
      icon: AlignLeftIcon,
      category: "ui",
    },
    toggle: {
      name: "Toggle",
      type: "registry:ui",
      href: "/toggle",
      icon: PowerIcon,
      category: "ui",
    },
    "toggle-group": {
      name: "Toggle Group",
      type: "registry:ui",
      href: "/toggle-group",
      icon: LayersIcon,
      category: "ui",
    },
    tooltip: {
      name: "Tooltip",
      type: "registry:ui",
      href: "/tooltip",
      icon: HelpCircleIcon,
      category: "ui",
    },
    "actions": {
      name: "Actions",
      type: "registry:ui",
      href: "/actions",
      icon: LayersIcon,
            category: "ai",
    },
    "branch": {
      name: "Branch",
      type: "registry:ui",
      href: "/branch",
      icon: LayersIcon,
              category: "ai",
    },
    "chain-of-thought": {
      name: "Chain of Thought",
      type: "registry:ui",
      href: "/chain-of-thought",
      icon: LayersIcon,
      category: "ui",
    },
    "checkpoint": {
      name: "Checkpoint",
      type: "registry:ui",
      href: "/checkpoint",
      icon: LayersIcon,
            category: "ai",
    },
    "code-block": {
      name: "Code Block",
      type: "registry:ui",
      href: "/code-block",
      icon: LayersIcon,
            category: "ai",
    },
    "confirmation": {
      name: "Confirmation",
      type: "registry:ui",
      href: "/confirmation",
      icon: LayersIcon,
            category: "ai",
    },
    "context": {
      name: "Context",
      type: "registry:ui",
      href: "/context",
      icon: LayersIcon,
            category: "ai",
    },
    "conversation": {
      name: "Conversation",
      type: "registry:ui",
      href: "/conversation",
      icon: LayersIcon,
      category: "ui",
    },  
    "feedbackbar": {
      name: "Feedback Bar",
      type: "registry:ui",
      href: "/feedbackbar",
      icon: LayersIcon,
      category: "ui",
    },
    "image": {
      name: "Image",
      type: "registry:ui",
      href: "/image",
      icon: LayersIcon,
      category: "ui",
    },
    "loader": {
      name: "Loader",
      type: "registry:ui",
      href: "/loader",
      icon: LayersIcon,
      category: "ui",
    },
    "links": {
      name: "Links",
      type: "registry:ui",
      href: "/links",
      icon: LayersIcon,
      category: "ui",
    },
    "inline-citation": {
      name: "Inline Citation",
      type: "registry:ui",
      href: "/inline-citation",
      icon: LayersIcon,
      category: "ui",
    },
    "message": {
      name: "Message",
      type: "registry:ui",
      href: "/message",
      icon: LayersIcon,
          category: "ai",
    },
    "model-selector": {
      name: "Model Selector",
      type: "registry:ui",
      href: "/model-selector",
      icon: LayersIcon,
          category: "ai",
    },
    "open-in-chat": {
      name: "Open in Chat",
      type: "registry:ui",
      href: "/open-in-chat",
      icon: LayersIcon,
          category: "ai",
    },
    "plan": {
      name: "Plan",
      type: "registry:ui",
      href: "/plan",
      icon: LayersIcon,
        category: "ai",
    },  
    "prompt-input": {
      name: "Prompt Input",
      type: "registry:ui",
      href: "/prompt-input",
      icon: LayersIcon,
        category: "ai",
    },
    "queue": {
      name: "Queue",
      type: "registry:ui",
      href: "/queue",
      icon: LayersIcon,
      category: "ai",
    },
    "reasoning": {
      name: "Reasoning",
      type: "registry:ui",
      href: "/reasoning",
      icon: LayersIcon,
      category: "ai",
    },
    "response": {
      name: "Response",
      type: "registry:ui",
      href: "/response",
      icon: LayersIcon,
          category: "ai",
    },
    "shimmer": {
      name: "Shimmer",
      type: "registry:ui",
      href: "/shimmer",
      icon: LayersIcon,
      category: "ui",
    },
    "sources": {
      name: "Sources",
      type: "registry:ui",
      href: "/sources",
      icon: LayersIcon,
      category: "ai",
    },
    "suggestions": {
      name: "Suggestions",
      type: "registry:ui",
      href: "/suggestions",
      icon: LayersIcon,
      category: "ai",
    },
    "task": {
      name: "Task",
      type: "registry:ui",
      href: "/task",
      icon: LayersIcon,
      category: "ui",
    },
    "tool": {
      name: "Tool",
      type: "registry:ui",
      href: "/tool",
      icon: LayersIcon,
      category: "ai",
    },
    "web-preview": {
      name: "Web Preview",
      type: "registry:ui",
      href: "/web-preview",
      icon: LayersIcon,
      category: "ai",
    },
  }
  
  export type ComponentKey = keyof typeof componentRegistry