import { 
    AlertCircleIcon, 
    BellDotIcon, 
    ComponentIcon, 
    LayoutDashboardIcon, 
    SidebarIcon, 
    WandIcon,
    FileTextIcon, 
    MessageCircleIcon,
    SquareIcon,
    UserIcon,
    StarIcon,
    ArrowRightIcon,
    MousePointerClickIcon,
    LayersIcon,
    CalendarIcon,
    CreditCardIcon,
    ArrowLeftRightIcon,
    CheckSquareIcon,
    ChevronDownIcon,
    SearchIcon,
    CommandIcon,
    MoreVerticalIcon,
    MessageSquareIcon,
    PanelLeftIcon,
    InboxIcon,
    TypeIcon,
    HashIcon,
    HelpCircleIcon,
    TagIcon,
    MenuIcon,
    ArrowLeftIcon,
    BarChart3Icon,
    CircleDotIcon,
    ExpandIcon,
    ArrowDownIcon,
    ChevronsUpDownIcon,
    MinusIcon,
    PanelRightIcon,
    LoaderIcon,
    SlidersIcon,
    PowerIcon,
    TableIcon,
    AlignLeftIcon,
    FolderRootIcon,
  } from "lucide-react"
  
  // Category configuration with icons
  export const categoryConfig: Record<
    string,
    { icon: React.FC; label?: string }
  > = {
    ai: { icon: WandIcon, label: "AI" },
    ui: { icon: ComponentIcon, label: "UI" },
    sidebar: { icon: SidebarIcon, label: "Sidebar" },
    dashboards: { icon: LayoutDashboardIcon, label: "Dashboards" },
    chat: { icon: MessageCircleIcon, label: "Chat" },
    page: { icon: FileTextIcon, label: "Page" },
  }

  type ComponentConfig = {
    name: string
    component?: React.ComponentType
    className?: string
    type: "registry:ui" | "registry:page" | "registry:block"
    href: string
    label?: string
    icon?: React.FC
    category?: string
  }
  
  export const componentRegistry: Record<string, ComponentConfig> = {
    accordion: {
      name: "Accordion",
      type: "registry:ui",
      href: "/sink/accordion",
      icon: FolderRootIcon,
      category: "ui",
    },
    alert: {
      name: "Alert",
      type: "registry:ui",
      href: "/sink/alert",
      icon: BellDotIcon,
      category: "ui",
    },
    "alert-dialog": {
      name: "Alert Dialog",
      type: "registry:ui",
      href: "/sink/alert-dialog",
      icon: AlertCircleIcon,
      category: "ui",
    },
    "aspect-ratio": {
      name: "Aspect Ratio",
      type: "registry:ui",
      href: "/sink/aspect-ratio",
      icon: SquareIcon,
      category: "ui",
    },
    avatar: {
      name: "Avatar",
      type: "registry:ui",
      href: "/sink/avatar",
      icon: UserIcon,
      category: "ui",
    },
    badge: {
      name: "Badge",
      type: "registry:ui",
      href: "/sink/badge",
      icon: StarIcon,
      category: "ui",
    },
    breadcrumb: {
      name: "Breadcrumb",
      type: "registry:ui",
      href: "/sink/breadcrumb",
      icon: ArrowRightIcon,
      category: "ui",
    },
    button: {
      name: "Button",
      type: "registry:ui",
      href: "/sink/button",
      icon: MousePointerClickIcon,
      category: "ui",
    },
    "button-group": {
      name: "Button Group",
      type: "registry:ui",
      href: "/sink/button-group",
      label: "New",
      icon: LayersIcon,
      category: "ui",
    },
    calendar: {
      name: "Calendar",
      type: "registry:ui",
      href: "/sink/calendar",
      icon: CalendarIcon,
      category: "ui",
    },
    card: {
      name: "Card",
      type: "registry:ui",
      href: "/sink/card",
      icon: CreditCardIcon,
      category: "ui",
    },
    carousel: {
      name: "Carousel",
      type: "registry:ui",
      href: "/sink/carousel",
      icon: ArrowLeftRightIcon,
      category: "ui",
    },
    chart: {
      name: "Chart",
      className: "w-full",
      type: "registry:ui",
      href: "/sink/chart",
      icon: BarChart3Icon,
      category: "ui",
    },
    checkbox: {
      name: "Checkbox",
      type: "registry:ui",
      href: "/sink/checkbox",
      icon: CheckSquareIcon,
      category: "ui",
    },
    collapsible: {
      name: "Collapsible",
      type: "registry:ui",
      href: "/sink/collapsible",
      icon: ChevronDownIcon,
      category: "ui",
    },
    combobox: {
      name: "Combobox",
      type: "registry:ui",
      href: "/sink/combobox",
      icon: SearchIcon,
      category: "ui",
    },
    command: {
      name: "Command",
      type: "registry:ui",
      href: "/sink/command",
      icon: CommandIcon,
      category: "ui",
    },
    "context-menu": {
      name: "Context Menu",
      type: "registry:ui",
      href: "/sink/context-menu",
      icon: MoreVerticalIcon,
      category: "ui",
    },
    "date-picker": {
      name: "Date Picker",
      type: "registry:ui",
      href: "/sink/date-picker",
      icon: CalendarIcon,
      category: "ui",
    },
    dialog: {
      name: "Dialog",
      type: "registry:ui",
      href: "/sink/dialog",
      icon: MessageSquareIcon,
      category: "ui",
    },
    drawer: {
      name: "Drawer",
      type: "registry:ui",
      href: "/sink/drawer",
      icon: PanelLeftIcon,
      category: "ui",
    },
    "dropdown-menu": {
      name: "Dropdown Menu",
      type: "registry:ui",
      href: "/sink/dropdown-menu",
      icon: ChevronDownIcon,
      category: "ui",
    },
    empty: {
      name: "Empty",
      type: "registry:ui",
      href: "/sink/empty",
      label: "New",
      icon: InboxIcon,
      category: "ui",
    },
    field: {
      name: "Field",
      type: "registry:ui",
      href: "/sink/field",
      label: "New",
      icon: FileTextIcon,
      category: "ui",
    },
    form: {
      name: "Form",
      type: "registry:ui",
      href: "/sink/form",
      icon: FileTextIcon,
      category: "ui",
    },
    "hover-card": {
      name: "Hover Card",
      type: "registry:ui",
      href: "/sink/hover-card",
      icon: MousePointerClickIcon,
      category: "ui",
    },
    input: {
      name: "Input",
      type: "registry:ui",
      href: "/sink/input",
      icon: TypeIcon,
      category: "ui",
    },
    "input-group": {
      name: "Input Group",
      type: "registry:ui",
      href: "/sink/input-group",
      label: "New",
      icon: LayersIcon,
      category: "ui",
    },
    "input-otp": {
      name: "Input OTP",
      type: "registry:ui",
      href: "/sink/input-otp",
      icon: HashIcon,
      category: "ui",
    },
    item: {
      name: "Item",
      type: "registry:ui",
      href: "/sink/item",
      label: "New",
      icon: FileTextIcon,
      category: "ui",
    },
    kbd: {
      name: "Kbd",
      type: "registry:ui",
      href: "/sink/kbd",
      label: "New",
      icon: CommandIcon,
      category: "ui",
    },
    label: {
      name: "Label",
      type: "registry:ui",
      href: "/sink/label",
      icon: TagIcon,
      category: "ui",
    },
    menubar: {
      name: "Menubar",
      type: "registry:ui",
      href: "/sink/menubar",
      icon: MenuIcon,
      category: "ui",
    },
    "navigation-menu": {
      name: "Navigation Menu",
      type: "registry:ui",
      href: "/sink/navigation-menu",
      icon: MenuIcon,
      category: "ui",
    },
    "native-select": {
      name: "Native Select",
      type: "registry:ui",
      href: "/sink/native-select",
      label: "New",
      icon: ChevronDownIcon,
      category: "ui",
    },
    pagination: {
      name: "Pagination",
      type: "registry:ui",
      href: "/sink/pagination",
      icon: ArrowLeftIcon,
      category: "ui",
    },
    popover: {
      name: "Popover",
      type: "registry:ui",
      href: "/sink/popover",
      icon: MessageCircleIcon,
      category: "ui",
    },
    progress: {
      name: "Progress",
      type: "registry:ui",
      href: "/sink/progress",
      icon: BarChart3Icon,
      category: "ui",
    },
    "radio-group": {
      name: "Radio Group",
      type: "registry:ui",
      href: "/sink/radio-group",
      icon: CircleDotIcon,
      category: "ui",
    },
    resizable: {
      name: "Resizable",
      type: "registry:ui",
      href: "/sink/resizable",
      icon: ExpandIcon,
      category: "ui",
    },
    "scroll-area": {
      name: "Scroll Area",
      type: "registry:ui",
      href: "/sink/scroll-area",
      icon: ArrowDownIcon,
      category: "ui",
    },
    select: {
      name: "Select",
      type: "registry:ui",
      href: "/sink/select",
      icon: ChevronsUpDownIcon,
      category: "ui",
    },
    separator: {
      name: "Separator",
      type: "registry:ui",
      href: "/sink/separator",
      icon: MinusIcon,
      category: "ui",
    },
    sheet: {
      name: "Sheet",
      type: "registry:ui",
      href: "/sink/sheet",
      icon: PanelRightIcon,
      category: "ui",
    },
    skeleton: {
      name: "Skeleton",
      type: "registry:ui",
      href: "/sink/skeleton",
      icon: LoaderIcon,
      category: "ui",
    },
    slider: {
      name: "Slider",
      type: "registry:ui",
      href: "/sink/slider",
      icon: SlidersIcon,
      category: "ui",
    },
    sonner: {
      name: "Sonner",
      type: "registry:ui",
      href: "/sink/sonner",
      icon: BellDotIcon,
      category: "ui",
    },
    spinner: {
      name: "Spinner",
      type: "registry:ui",
      href: "/sink/spinner",
      label: "New",
      icon: LoaderIcon,
      category: "ui",
    },
    switch: {
      name: "Switch",
      type: "registry:ui",
      href: "/sink/switch",
      icon: PowerIcon,
      category: "ui",
    },
    table: {
      name: "Table",
      type: "registry:ui",
      href: "/sink/table",
      icon: TableIcon,
      category: "ui",
    },
    tabs: {
      name: "Tabs",
      type: "registry:ui",
      href: "/sink/tabs",
      icon: LayersIcon,
      category: "ui",
    },
    textarea: {
      name: "Textarea",
      type: "registry:ui",
      href: "/sink/textarea",
      icon: AlignLeftIcon,
      category: "ui",
    },
    toggle: {
      name: "Toggle",
      type: "registry:ui",
      href: "/sink/toggle",
      icon: PowerIcon,
      category: "ui",
    },
    "toggle-group": {
      name: "Toggle Group",
      type: "registry:ui",
      href: "/sink/toggle-group",
      icon: LayersIcon,
      category: "ui",
    },
    tooltip: {
      name: "Tooltip",
      type: "registry:ui",
      href: "/sink/tooltip",
      icon: HelpCircleIcon,
      category: "ui",
    },
  }
  
  export type ComponentKey = keyof typeof componentRegistry